version: '3.8'

services:
  # Banco de Dados Relacional
  postgres:
    image: postgres:16-alpine
    container_name: eventpulse-postgres
    restart: always
    environment:
      POSTGRES_USER: eventpulse_user
      POSTGRES_PASSWORD: eventpulse_pass
      POSTGRES_DB: eventpulse_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Broker de Mensagens (RabbitMQ)
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: eventpulse-rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"   # Porta do AMQP (para a aplicação se conectar)
      - "15672:15672" # Porta do Dashboard Web Management
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  postgres_data:
  rabbitmq_data: